accelerate==0.27.2
aiohappyeyeballs==2.6.1
aiohttp==3.11.18
aiosignal==1.3.2
attrs==25.3.0
certifi==2025.8.3
charset-normalizer==3.4.3
contourpy==1.3.3
cycler==0.12.1
datasets==3.6.0
dill==0.3.8
filelock==3.19.1
fonttools==4.59.2
frozenlist==1.6.0
fsspec==2025.7.0
hf-xet==1.1.8
huggingface_hub==0.34.4
idna==3.10
imbalanced-learn==0.14.0
inquirerpy==0.3.4
Jinja2==3.1.6
joblib==1.5.1
kiwisolver==1.4.9
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.10.6
mdurl==0.1.2
mpmath==1.3.0
multidict==6.4.3
multiprocess==0.70.16
networkx==3.5
numpy==1.26.4
packaging==25.0
pandas==2.2.3
pfzy==0.3.4
pillow==11.3.0
prompt_toolkit==3.0.51
propcache==0.3.1
psutil==7.0.0
pyarrow==20.0.0
Pygments==2.19.2
pyparsing==3.2.3
python-dateutil==2.9.0.post0
pytz==2025.2
PyYAML==6.0.2
regex==2025.7.33
requests==2.32.5
rich==14.1.0
safetensors==0.5.3
scikit-learn==1.7.1
scipy==1.16.1
seaborn==0.13.2
sentence-transformers==5.0.0
setuptools==80.9.0
six==1.17.0
sympy==1.14.0
threadpoolctl==3.6.0
tokenizers==0.21.4
torch==2.7.1
torchsummary==1.5.1
tqdm==4.67.1
transformers==4.54.1
typing_extensions==4.15.0
tzdata==2025.2
urllib3==2.5.0
wcwidth==0.2.13
xxhash==3.5.0
yarl==1.20.0
